version: '3.9'

services:
#  nginx:
#    build: './nginx'
#    ports:
#      - '80:80'
#
#  frontend:
#    build: './frontend'
#    env_file:
#      - ./frontend/.env
#
#  backend:
#    build: './backend'
#    env_file:
#      - ./backend/.env

  db:
    build: './db'
    volumes:
      - 'db_data:/var/lib/postgresql/data/'
    env_file:
      - ./db/.env
    ports:
      - '5432:5432'


volumes:
  db_data:
