version: '3.9'

services:
  frontend:
    build: './frontend'
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'

  backend:
    build: './backend'
    env_file:
      - ./backend/.env
    ports:
      - '4000:4000'

  db:
    build: './db'
    volumes:
      - 'db_data:/var/lib/postgresql/data/'
    env_file:
      - ./db/.env
    ports:
      - '5432:5432'

volumes:
  db_data:
